"""Generate tests/coverage_report.md — per-module Public function test coverage."""
import os, re, sys
from pathlib import Path
from datetime import date

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = PROJECT_ROOT / "src"
VBA_CORE_DIR = PROJECT_ROOT / "VBA-Core"
CROSSVAL_DIR = PROJECT_ROOT / "tests" / "crossval"
INTEGRATION_TEST = PROJECT_ROOT / "tests" / "utils" / "integration_test_all_modules.py"
OUTPUT = PROJECT_ROOT / "tests" / "coverage_report.md"

RE_PUBLIC = re.compile(r'^Public\s+(?:Function|Sub)\s+(\w+)', re.MULTILINE)


def extract_public_functions(path: Path) -> list[str]:
    """Extract all Public Function/Sub names from a .bas/.cls file."""
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    return RE_PUBLIC.findall(text)


def load_test_corpus() -> str:
    """Load all test source files into a single searchable string.

    For VBA source files, only Test_* sub bodies are included to avoid
    self-referencing (a function matching its own definition).
    """
    parts = []
    # Cross-validation build scripts
    if CROSSVAL_DIR.exists():
        for f in CROSSVAL_DIR.glob("*.py"):
            parts.append(f.read_text(encoding="utf-8", errors="replace"))
    # Integration test
    if INTEGRATION_TEST.exists():
        parts.append(INTEGRATION_TEST.read_text(encoding="utf-8", errors="replace"))
    # VBA unit tests: extract only Test_* sub bodies from source files
    re_test_sub = re.compile(
        r'^Public Sub Test_\w+.*?^End Sub',
        re.MULTILINE | re.DOTALL
    )
    for d in (SRC_DIR, VBA_CORE_DIR):
        for f in d.glob("*.*"):
            if f.suffix in (".bas", ".cls"):
                text = f.read_text(encoding="utf-8-sig", errors="replace")
                for m in re_test_sub.finditer(text):
                    parts.append(m.group(0))
    return "\n".join(parts)


def check_coverage(func_name: str, corpus: str) -> bool:
    """Check if a function name appears in the test corpus."""
    # Case-insensitive search (VBA is case-insensitive)
    return func_name.lower() in corpus.lower()


def main():
    corpus = load_test_corpus()

    # Collect modules
    modules = []
    # VBA-Core first
    for f in sorted(VBA_CORE_DIR.glob("*.cls")):
        modules.append(("VBA-Core", f.stem, f))
    # src/ modules
    for f in sorted(SRC_DIR.glob("*.bas")):
        modules.append(("src", f.stem, f))

    total_funcs = 0
    total_covered = 0
    rows = []

    for layer, mod_name, path in modules:
        funcs = extract_public_functions(path)
        covered = [fn for fn in funcs if check_coverage(fn, corpus)]
        uncovered = [fn for fn in funcs if not check_coverage(fn, corpus)]
        n = len(funcs)
        c = len(covered)
        pct = (c / n * 100) if n > 0 else 0
        total_funcs += n
        total_covered += c
        rows.append((layer, mod_name, n, c, pct, uncovered))

    # Generate markdown
    lines = [
        "# Test Coverage Report",
        "",
        f"> Auto-generated by `scripts/generate_coverage.py` on {date.today().isoformat()}",
        f"> Method: function-name presence in crossval + integration + VBA unit test corpus",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Public functions | {total_funcs} |",
        f"| Covered by tests | {total_covered} |",
        f"| **Coverage rate** | **{total_covered/total_funcs*100:.1f}%** |",
        f"| Modules | {len(rows)} |",
        "",
        "## Per-Module Breakdown",
        "",
        "| Module | Layer | Public | Covered | Rate | Uncovered |",
        "|--------|-------|--------|---------|------|-----------|",
    ]

    for layer, mod_name, n, c, pct, uncovered in rows:
        unc_str = ", ".join(uncovered[:5]) if uncovered else "-"
        if len(uncovered) > 5:
            unc_str += f" (+{len(uncovered)-5} more)"
        lines.append(f"| {mod_name} | {layer} | {n} | {c} | {pct:.0f}% | {unc_str} |")

    lines += [
        "",
        "## Notes",
        "",
        "- **Coverage method**: A function is 'covered' if its name appears in any test file",
        "  (crossval build_*.py, integration_test_all_modules.py, or VBA Test_* sub bodies).",
        "  Source file definitions are excluded to prevent self-referencing.",
        "- UDF wrappers (UDF_*) are tested via the UDF-Range-xlsm crossval tier.",
        "- Internal helpers (Private) are implicitly covered through Public entry points.",
        "- 2 crossval SKIPs (COM Range-pair marshaling) are documented limitations.",
        "",
        "### Method Limitations",
        "",
        "- **Name-presence ≠ behavioral verification**: A function name appearing in a test",
        "  file (even in a comment) counts as 'covered'. This metric measures test *awareness*,",
        "  not assertion-level behavioral coverage.",
        "- **UDF wrappers**: UDF_* delegates are 1-line wrappers tested indirectly via their",
        "  core function's crossval test. They appear as 'uncovered' because the crossval calls",
        "  the core function name (e.g., `ArrayUnique`) not the UDF name (e.g., `UDF_ARR_UNIQUE`).",
        "- **Count scope**: This report counts ALL Public Function/Sub in `src/*.bas` and",
        "  `VBA-Core/*.cls` (including Test_* harnesses). `rules/api-reference.md` counts only",
        "  documented API functions (excluding Test_* subs), so its total is lower.",
        "- For true behavioral coverage, run cross-validation (`run_all_crossval.py`) and",
        "  integration tests (`integration_test_all_modules.py`) on a Windows + Excel environment.",
        "",
    ]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {OUTPUT}")
    print(f"  Total: {total_funcs} functions, {total_covered} covered ({total_covered/total_funcs*100:.1f}%)")


if __name__ == "__main__":
    main()
